---
language: go
go:
  - "1.11.x"
  - "1.12.x"

services:
  - redis-server

before_install:
  # update to latest version of redis
  - sudo apt-get install -y redis-server
  - GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.17.1

script:
  # for some reason go test -v -race ./... doesn't work on travis, so use this
  - cd v3
  - go list ./... | xargs -n1 go test -v -race
  - golangci-lint run -D errcheck -E goimports -E golint -E misspell -E stylecheck -E unconvert

after_failure:
  - tail -n100 ./*.log
