---
language: go
go:
  - "1.11.x"
  - "1.12.x"

services:
  - redis-server

before_install:
  # update to latest version of redis
  - sudo apt-get install -y redis-server

script:
  # for some reason go test -v -race ./... doesn't work on travis, so use this
  - go list ./... | xargs -n1 go test -v -race

after_failure:
  - tail -n100 ./*.log
